### ISSUE TITLE
Understanding needed for Native App embedded Browsers

### ISSUE THREAD

**Issue by codestorycooked** [auth0/auth0-oidc-client-net#184]
As per the [OAuth 2.0 Best Current Practice for Native Apps](https://auth0.com/blog/oauth-2-best-practices-for-native-apps/#OAuth-2-0-Best-Current-Practice-for-Native-Apps), we should not embed browser component into the library. Then why Auth0 is embedding user-agents in nuget-package? Say for example for WPF, WindowForm or for Andriod. 

Is my understanding correct about embedded user-agents vs external user-agents as spec clearly mentions that embedded user-agents or webview based user-agents are not recommended?

Take the example of **Auth0.OidcClient.WPF** nuget package, it is embedding Webview to show Internet Explorer or Microsoft Edge

**RFC 8252**
_For authorizing users in native apps, the best current practice is to perform the OAuth authorization request in an external user-agent (typically the browser) rather than an embedded user-agent (such as one implemented with web-views)._

Please help me in this regard and help me understand.

**Comment by frederikprijck** [comment]
Hey @codestorycooked ,

I think it is important to make a difference here between mobile and desktop apps.
For mobile apps, our SDKs use System Browsers and avoid using embedded browsers. This is because of the fact that this is easy to implement in a secure way.

However, on desktop applications, we rely on using embedded browsers because of the fact that using system browsers on desktop applications needs a bit of a different approach as opposed to mobile applications, which would open other security vulnerabilities.

Let me elaborate a bit more... Mobile and Native applications are recommended to use Authorization Code with PKCE flow, this flow works like this:

- Application X (mobile or desktop) initializes the flow by calling login and **redirecting to auth0**
- User enters their credentials **on the login page on Auth0**
- Auth0 redirects back to your application and includes `code` and `state` in the URL
- Your application reads the code parameter from the URL and exchanges it for a token by doing an HTTP Post.

The important part I want to highlight here is this step:
- Your application reads the code parameter from the URL and exchanges it for a token by doing an HTTP Post.

In order to be able to do this, you application needs to be able to intercept that URL, handle it, parse the parameters and use them. In mobile applications this is easy using custom schemes.

On desktop applications such as WPF and Winforms, it is a lot harder to have your application react to a URL, lets say, `https://my-wpf-application.com/callback`. This is because of the nature of winforms and WPF, there is no easy built in way to have your application handle URLs.

A solution here is to, temporarily, spin up a web server inside of your WPF / Winforms application that listens to `localhost;1234/callback` and ensure Auth0 redirects back to that URL. This would work, and some other SDKs use this pattern, but this has the following problems:

- Opening up a web server allows for attackers to also call that URL.
- localhost isn't recommended for this, but there is not much you can change about that as it really is a localhost webserver
- To limit the vulnerability, you need to ensure the webserver is properly closed once the URL is handled.

There are probably more issues with that approach. All of this is why we believe sticking to embedded browsers in our desktop applications for .NET is a good idea. Especially given WebView 2, where Microsoft is showing to be investing a lot in their embedded browser.

I hope this helps you understand the difference a little bit between mobile and desktop applications and why we are not using system browsers but make use of embedded browsers on our desktop applications.

**Comment by frederikprijck** [comment]
Closing as answered, feel free to continue conversation.

**Comment by codestorycooked** [comment]
Thank you @frederikprijck for a detailed explanation. I will get back to my team with this.
