### ISSUE TITLE
Mobile app - Close the web browser after login

### ISSUE THREAD

**Issue by fmarkov** [auth0/auth0-oidc-client-net#21]
We have a Xamarin mobile app for both iOS and Android.  We used to use the  component that launches a webview with the login page, and that's deprecated.  Now it launches the phones default browser.  The issue is it stays open behind the app with a spinning circle even when a good login occurs.  How do we have the web browser automatically close on good login?

**Comment by lorenh** [comment]
I've just had a discussion over on the Lock repository with luisrudge ( https://github.com/auth0/lock/issues/1511 ) and he is saying this issue is due to a lack of support by the Auth0.OidcClient.Android for Custom Tabs on Android.  Can we please get support added for this in this component so that the tab can properly close?

**Comment by lbalmaceda** [comment]
@lorenh one of the advantages of using Chrome Custom Tabs (CCT) is that you never leave your application when you open the new browser activity. This way when the result comes back, we can clear the activities stack above that authentication activity and the CCT disappears from the history. If you manage to find and use a xamarin plugin that works using CCT, you can check our code in the `WebAuthProvider` class (and related) on the auth0.android repository to see how to achieve this result.

**Comment by lorenh** [comment]
@lbalmaceda I want to make sure I understand what you are saying, so bear with me if I'm asking dumb questions here... so are you in agreement that the Auth0.OidcClient.Android component could theoretically be modified to take advantage of CCT and dropped in without any significant modifications to our app?  Or are you not the person to ask?

**Comment by lbalmaceda** [comment]
@lorenh I can't say because I'm not familiar with this SDK nor .Net. It's not just adding Android CCT support but also handling the activities flow/stack as it's done in the Android SDK I mentioned above, so it's not a simple change one could do just by using a different plugin or bumping the version. (Unless that plugin handles this already)

**Comment by lorenh** [comment]
So do we just wait until someone who is familiar with this SDK chimes in?  @jerriep, @luminousAvocado, @nicosabena

**Comment by jerriep** [comment]
@lorenh I do not work for Auth0 anymore

**Comment by lorenh** [comment]
Is there any reason we could not use the Xamarin.Auth library instead of this component with Auth0?

**Comment by lorenh** [comment]
We may have just found a solution to using Chrome Custom Tabs instead of system browser on Android. (Time will tell as we implement it in our application for real).

Because the Auth0 component is just a thin shim over IdentityModel.OidcClient, a search eventually led me to this very simple sample which provides an alternate IBrowser implementation that displays the login page in a custom tab.

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/AndroidClientChromeCustomTabs/AndroidClientChromeCustomTabs/ChromeCustomTabsWebView.cs

I am just leaving a comment here to possibly save someone else time going down the same path.

**Comment by kraln** [comment]
I'd like to voice my support for this to be addressed.

**Comment by damieng** [comment]
Chrome custom tabs are used by default in the next version of this SDK.

**Comment by elvenprogrammer** [comment]
I do still have the problem of login pages not closed and remaining in browser history after a successfull login. Using latest Xamarin Android version

**Comment by lbalmaceda** [comment]
@elvenprogrammer 
> login pages not closed and remaining in browser history

The browser apps don't expose an API that lets you control that on Android. 

The best you can do is have activity "A" _start the authentication_ by launching a new activity "B" that will open the authentication in a Custom Tab (which might not be available in the device) or an "external" browser session. Then when the browser calls back your app, it should call back into activity "C" which would launch "B" again but with a special flag for clearing the stack (see flag [CLEAR_TOP](https://developer.android.com/guide/components/activities/tasks-and-back-stack#Clearing)). "B" would take care of parsing the result and making the final token exchange request. Anyways, doing the above is still not going to resolve your issue when the device doesn't support Custom Tabs. cc @frederikprijck
