### ISSUE TITLE
how to get the roles of user

### ISSUE THREAD

**Issue by deRightDirection** [auth0/auth0-oidc-client-net#52]
```csharp
 var client = new Auth0Client(new Auth0ClientOptions
            {
                Domain = domain,
                ClientId = clientId,
                Scope = "openid profile email roles"
            });
```

i use the latest version of the nuget-package

in my user i can't read the role which the user belongs too :-(

how can i do this?

**Comment by damieng** [comment]
Hi there.

`roles` is neither a standard OpenID scope nor an Auth0 one so that wouldn't bring them back.

What you can do is put a rule on the server side that adds them to the id token as a custom claim, we have some details on this at https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims
